repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format
        args: [-i, --Werror]
        language: system
        files: \.(cpp|hpp|h|c|cxx|cc)$
